package sinon.views;

import java.awt.Color;
import java.awt.Dimension;

import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 * TODO
 * 
 * @author Josh Desmond
 */
@SuppressWarnings("serial")
public class InfoPanel extends JPanel {

    /**
     * TODO
     */
    public InfoPanel() {
        // This code was generated by the window builder I don't even know.
        this.setPreferredSize(new Dimension(180, 800));
        this.setMinimumSize(new Dimension(150, 800));
        this.setBorder(new LineBorder(new Color(0, 0, 0)));
        this.setLayout(null);
    }
}
